name: build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      - develop

jobs:
  Windows_32bit:
    runs-on: blacksmith-4vcpu-windows-2025
    steps:
      - uses: actions/checkout@v6
      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B build -A Win32
      - name: Build
        run: cmake --build build --config Release
      - uses: actions/upload-artifact@v4
        with:
          name: xiloader
          path: xiloader.exe
          if-no-files-found: error
